language: python
cache: pip
python:
- "3.7"
- "3.8"
- "3.9"
- "3.10"
- "3.11"

install:
  - python --version
  - pip --version
  - pip install --upgrade setuptools numpy
  - pip install typing-extensions
  - pip install .
  - pip list

script:
  - pytest -Wignore
  - ladim_aggregate --example grid_2D
  - ladim_aggregate aggregate.yaml
