language: python
python:
- "3.6"
- "3.7"
- "3.8"
- "3.9"

install:
  - python --version
  - pip --version
  - pip install --upgrade setuptools numpy
  - pip install typing-extensions
  - pip install .
  - pip list

script:
  - pytest
